INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_GAUSSIAN_CODE gaussian_code)

FIND_PATH(
    GAUSSIAN_CODE_INCLUDE_DIRS
    NAMES gaussian_code/api.h
    HINTS $ENV{GAUSSIAN_CODE_DIR}/include
        ${PC_GAUSSIAN_CODE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GAUSSIAN_CODE_LIBRARIES
    NAMES gnuradio-gaussian_code
    HINTS $ENV{GAUSSIAN_CODE_DIR}/lib
        ${PC_GAUSSIAN_CODE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GAUSSIAN_CODE DEFAULT_MSG GAUSSIAN_CODE_LIBRARIES GAUSSIAN_CODE_INCLUDE_DIRS)
MARK_AS_ADVANCED(GAUSSIAN_CODE_LIBRARIES GAUSSIAN_CODE_INCLUDE_DIRS)

